# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(BN-XML_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(BN-XML_INCLUDE_DIRS)
   

find_library(BN-XML_DEBUG_LIBRARY bn-xml_d)
find_library(BN-XML_LIBRARY       bn-xml)


if (BN-XML_DEBUG_LIBRARY)
  set(BN-XML_LIBRARIES optimized;${BN-XML_LIBRARY};debug;${BN-XML_DEBUG_LIBRARY})
else()
  set(BN-XML_LIBRARIES ${BN-XML_LIBRARY})
endif()

set(BN-XML_LIBRARIES ${BN-XML_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BN-XML DEFAULT_MSG
  BN-XML_LIBRARIES
  BN-XML_INCLUDE_DIRS
)
set(BN-XML_PACKAGE_FOUND ${BN-XML_FOUND} CACHE INTERNAL "" FORCE)
 
set(BN-XML_DEPENDS "" CACHE INTERNAL "" FORCE)
 