# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(BN-RT_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(BN-RT_INCLUDE_DIRS)
   

find_library(BN-RT_DEBUG_LIBRARY bn-rt_d)
find_library(BN-RT_LIBRARY       bn-rt)


if (BN-RT_DEBUG_LIBRARY)
  set(BN-RT_LIBRARIES optimized;${BN-RT_LIBRARY};debug;${BN-RT_DEBUG_LIBRARY})
else()
  set(BN-RT_LIBRARIES ${BN-RT_LIBRARY})
endif()

set(BN-RT_LIBRARIES ${BN-RT_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BN-RT DEFAULT_MSG
  BN-RT_LIBRARIES
  BN-RT_INCLUDE_DIRS
)
set(BN-RT_PACKAGE_FOUND ${BN-RT_FOUND} CACHE INTERNAL "" FORCE)
 
set(BN-RT_DEPENDS "BOOST;PTHREAD;RT" CACHE INTERNAL "" FORCE)
 