# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALNAOSIM_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALNAOSIM_INCLUDE_DIRS)
   

find_library(ALNAOSIM_DEBUG_LIBRARY alnaosim_d)
find_library(ALNAOSIM_LIBRARY       alnaosim)


if (ALNAOSIM_DEBUG_LIBRARY)
  set(ALNAOSIM_LIBRARIES optimized;${ALNAOSIM_LIBRARY};debug;${ALNAOSIM_DEBUG_LIBRARY})
else()
  set(ALNAOSIM_LIBRARIES ${ALNAOSIM_LIBRARY})
endif()

set(ALNAOSIM_LIBRARIES ${ALNAOSIM_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALNAOSIM DEFAULT_MSG
  ALNAOSIM_LIBRARIES
  ALNAOSIM_INCLUDE_DIRS
)
set(ALNAOSIM_PACKAGE_FOUND ${ALNAOSIM_FOUND} CACHE INTERNAL "" FORCE)
 
set(ALNAOSIM_DEPENDS "QI" CACHE INTERNAL "" FORCE)
 