# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(BN-SPY_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(BN-SPY_INCLUDE_DIRS)
   

find_library(BN-SPY_DEBUG_LIBRARY bn-spy_d)
find_library(BN-SPY_LIBRARY       bn-spy)


if (BN-SPY_DEBUG_LIBRARY)
  set(BN-SPY_LIBRARIES optimized;${BN-SPY_LIBRARY};debug;${BN-SPY_DEBUG_LIBRARY})
else()
  set(BN-SPY_LIBRARIES ${BN-SPY_LIBRARY})
endif()

set(BN-SPY_LIBRARIES ${BN-SPY_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BN-SPY DEFAULT_MSG
  BN-SPY_LIBRARIES
  BN-SPY_INCLUDE_DIRS
)
set(BN-SPY_PACKAGE_FOUND ${BN-SPY_FOUND} CACHE INTERNAL "" FORCE)
 
set(BN-SPY_DEPENDS "USB;BN-COMMON;BOOST;BOOST_FILESYSTEM;BOOST_SYSTEM;DL" CACHE INTERNAL "" FORCE)
 