# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_semanticminer', [dirname(__file__)])
        except ImportError:
            import _semanticminer
            return _semanticminer
        if fp is not None:
            try:
                _mod = imp.load_module('_semanticminer', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _semanticminer = swig_import_helper()
    del swig_import_helper
else:
    import _semanticminer
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _semanticminer.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _semanticminer.SwigPyIterator_value(self)
    def incr(self, n=1): return _semanticminer.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _semanticminer.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _semanticminer.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _semanticminer.SwigPyIterator_equal(self, *args)
    def copy(self): return _semanticminer.SwigPyIterator_copy(self)
    def next(self): return _semanticminer.SwigPyIterator_next(self)
    def __next__(self): return _semanticminer.SwigPyIterator___next__(self)
    def previous(self): return _semanticminer.SwigPyIterator_previous(self)
    def advance(self, *args): return _semanticminer.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _semanticminer.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _semanticminer.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _semanticminer.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _semanticminer.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _semanticminer.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _semanticminer.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _semanticminer.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _semanticminer.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _semanticminer.IntVector___nonzero__(self)
    def __bool__(self): return _semanticminer.IntVector___bool__(self)
    def __len__(self): return _semanticminer.IntVector___len__(self)
    def pop(self): return _semanticminer.IntVector_pop(self)
    def __getslice__(self, *args): return _semanticminer.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _semanticminer.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _semanticminer.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _semanticminer.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _semanticminer.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _semanticminer.IntVector___setitem__(self, *args)
    def append(self, *args): return _semanticminer.IntVector_append(self, *args)
    def empty(self): return _semanticminer.IntVector_empty(self)
    def size(self): return _semanticminer.IntVector_size(self)
    def clear(self): return _semanticminer.IntVector_clear(self)
    def swap(self, *args): return _semanticminer.IntVector_swap(self, *args)
    def get_allocator(self): return _semanticminer.IntVector_get_allocator(self)
    def begin(self): return _semanticminer.IntVector_begin(self)
    def end(self): return _semanticminer.IntVector_end(self)
    def rbegin(self): return _semanticminer.IntVector_rbegin(self)
    def rend(self): return _semanticminer.IntVector_rend(self)
    def pop_back(self): return _semanticminer.IntVector_pop_back(self)
    def erase(self, *args): return _semanticminer.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _semanticminer.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _semanticminer.IntVector_push_back(self, *args)
    def front(self): return _semanticminer.IntVector_front(self)
    def back(self): return _semanticminer.IntVector_back(self)
    def assign(self, *args): return _semanticminer.IntVector_assign(self, *args)
    def resize(self, *args): return _semanticminer.IntVector_resize(self, *args)
    def insert(self, *args): return _semanticminer.IntVector_insert(self, *args)
    def reserve(self, *args): return _semanticminer.IntVector_reserve(self, *args)
    def capacity(self): return _semanticminer.IntVector_capacity(self)
    __swig_destroy__ = _semanticminer.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _semanticminer.IntVector_swigregister
IntVector_swigregister(IntVector)

class FloatVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _semanticminer.FloatVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _semanticminer.FloatVector___nonzero__(self)
    def __bool__(self): return _semanticminer.FloatVector___bool__(self)
    def __len__(self): return _semanticminer.FloatVector___len__(self)
    def pop(self): return _semanticminer.FloatVector_pop(self)
    def __getslice__(self, *args): return _semanticminer.FloatVector___getslice__(self, *args)
    def __setslice__(self, *args): return _semanticminer.FloatVector___setslice__(self, *args)
    def __delslice__(self, *args): return _semanticminer.FloatVector___delslice__(self, *args)
    def __delitem__(self, *args): return _semanticminer.FloatVector___delitem__(self, *args)
    def __getitem__(self, *args): return _semanticminer.FloatVector___getitem__(self, *args)
    def __setitem__(self, *args): return _semanticminer.FloatVector___setitem__(self, *args)
    def append(self, *args): return _semanticminer.FloatVector_append(self, *args)
    def empty(self): return _semanticminer.FloatVector_empty(self)
    def size(self): return _semanticminer.FloatVector_size(self)
    def clear(self): return _semanticminer.FloatVector_clear(self)
    def swap(self, *args): return _semanticminer.FloatVector_swap(self, *args)
    def get_allocator(self): return _semanticminer.FloatVector_get_allocator(self)
    def begin(self): return _semanticminer.FloatVector_begin(self)
    def end(self): return _semanticminer.FloatVector_end(self)
    def rbegin(self): return _semanticminer.FloatVector_rbegin(self)
    def rend(self): return _semanticminer.FloatVector_rend(self)
    def pop_back(self): return _semanticminer.FloatVector_pop_back(self)
    def erase(self, *args): return _semanticminer.FloatVector_erase(self, *args)
    def __init__(self, *args): 
        this = _semanticminer.new_FloatVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _semanticminer.FloatVector_push_back(self, *args)
    def front(self): return _semanticminer.FloatVector_front(self)
    def back(self): return _semanticminer.FloatVector_back(self)
    def assign(self, *args): return _semanticminer.FloatVector_assign(self, *args)
    def resize(self, *args): return _semanticminer.FloatVector_resize(self, *args)
    def insert(self, *args): return _semanticminer.FloatVector_insert(self, *args)
    def reserve(self, *args): return _semanticminer.FloatVector_reserve(self, *args)
    def capacity(self): return _semanticminer.FloatVector_capacity(self)
    __swig_destroy__ = _semanticminer.delete_FloatVector
    __del__ = lambda self : None;
FloatVector_swigregister = _semanticminer.FloatVector_swigregister
FloatVector_swigregister(FloatVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    def iterator(self): return _semanticminer.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _semanticminer.StringVector___nonzero__(self)
    def __bool__(self): return _semanticminer.StringVector___bool__(self)
    def __len__(self): return _semanticminer.StringVector___len__(self)
    def pop(self): return _semanticminer.StringVector_pop(self)
    def __getslice__(self, *args): return _semanticminer.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _semanticminer.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _semanticminer.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _semanticminer.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _semanticminer.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _semanticminer.StringVector___setitem__(self, *args)
    def append(self, *args): return _semanticminer.StringVector_append(self, *args)
    def empty(self): return _semanticminer.StringVector_empty(self)
    def size(self): return _semanticminer.StringVector_size(self)
    def clear(self): return _semanticminer.StringVector_clear(self)
    def swap(self, *args): return _semanticminer.StringVector_swap(self, *args)
    def get_allocator(self): return _semanticminer.StringVector_get_allocator(self)
    def begin(self): return _semanticminer.StringVector_begin(self)
    def end(self): return _semanticminer.StringVector_end(self)
    def rbegin(self): return _semanticminer.StringVector_rbegin(self)
    def rend(self): return _semanticminer.StringVector_rend(self)
    def pop_back(self): return _semanticminer.StringVector_pop_back(self)
    def erase(self, *args): return _semanticminer.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _semanticminer.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _semanticminer.StringVector_push_back(self, *args)
    def front(self): return _semanticminer.StringVector_front(self)
    def back(self): return _semanticminer.StringVector_back(self)
    def assign(self, *args): return _semanticminer.StringVector_assign(self, *args)
    def resize(self, *args): return _semanticminer.StringVector_resize(self, *args)
    def insert(self, *args): return _semanticminer.StringVector_insert(self, *args)
    def reserve(self, *args): return _semanticminer.StringVector_reserve(self, *args)
    def capacity(self): return _semanticminer.StringVector_capacity(self)
    def __repr__(self): return _semanticminer.StringVector___repr__(self)
    __swig_destroy__ = _semanticminer.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _semanticminer.StringVector_swigregister
StringVector_swigregister(StringVector)


def getRelatedness(*args):
  return _semanticminer.getRelatedness(*args)
getRelatedness = _semanticminer.getRelatedness
class Relatedness(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Relatedness, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Relatedness, name)
    def __init__(self, *args): 
        this = _semanticminer.new_Relatedness(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _semanticminer.delete_Relatedness
    __del__ = lambda self : None;
    def str(self): return _semanticminer.Relatedness_str(self)
    def getUnknownTags(self): return _semanticminer.Relatedness_getUnknownTags(self)
    def getKnownTags(self): return _semanticminer.Relatedness_getKnownTags(self)
    def getScores(self): return _semanticminer.Relatedness_getScores(self)
    def getKnownTagScores(self, *args): return _semanticminer.Relatedness_getKnownTagScores(self, *args)
    def getUnknownTagScores(self, *args): return _semanticminer.Relatedness_getUnknownTagScores(self, *args)
    def get(self, *args): return _semanticminer.Relatedness_get(self, *args)
    def getKnownTagMax(self, *args): return _semanticminer.Relatedness_getKnownTagMax(self, *args)
    def getUnknownTagMax(self, *args): return _semanticminer.Relatedness_getUnknownTagMax(self, *args)
    def getKnownTagAvg(self, *args): return _semanticminer.Relatedness_getKnownTagAvg(self, *args)
    def getUnknownTagAvg(self, *args): return _semanticminer.Relatedness_getUnknownTagAvg(self, *args)
    def isEmpty(self): return _semanticminer.Relatedness_isEmpty(self)
    def getMax(self): return _semanticminer.Relatedness_getMax(self)
    def getAvg(self): return _semanticminer.Relatedness_getAvg(self)
    def __repr__(self): return _semanticminer.Relatedness___repr__(self)
Relatedness_swigregister = _semanticminer.Relatedness_swigregister
Relatedness_swigregister(Relatedness)

# This file is compatible with both classic and new-style classes.


