# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(TINYXML_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(TINYXML_INCLUDE_DIRS)
   

find_library(TINYXML_DEBUG_LIBRARY tinyxml_d)
find_library(TINYXML_LIBRARY       tinyxml)


if (TINYXML_DEBUG_LIBRARY)
  set(TINYXML_LIBRARIES optimized;${TINYXML_LIBRARY};debug;${TINYXML_DEBUG_LIBRARY})
else()
  set(TINYXML_LIBRARIES ${TINYXML_LIBRARY})
endif()

set(TINYXML_LIBRARIES ${TINYXML_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TINYXML DEFAULT_MSG
  TINYXML_LIBRARIES
  TINYXML_INCLUDE_DIRS
)
set(TINYXML_PACKAGE_FOUND ${TINYXML_FOUND} CACHE INTERNAL "" FORCE)
 
set(TINYXML_DEPENDS "" CACHE INTERNAL "" FORCE)
 