#ifndef __GENERATED_alproxies__
#define __GENERATED_alproxies__
#include <alproxies/almovementdetectionproxy.h>
#include <alproxies/alfastpersontrackingproxy.h>
#include <alproxies/alaudioplayerproxy.h>
#include <alproxies/alredballtrackerproxy.h>
#include <alproxies/albonjourproxy.h>
#include <alproxies/alsensorsproxy.h>
#include <alproxies/alchestbuttonproxy.h>
#include <alproxies/alcolorblobdetectionproxy.h>
#include <alproxies/alresourcemanagerproxy.h>
#include <alproxies/algazeanalysisproxy.h>
#include <alproxies/albodytemperatureproxy.h>
#include <alproxies/alpythonbridgeproxy.h>
#include <alproxies/alphotocaptureproxy.h>
#include <alproxies/alsittingpeopledetectionproxy.h>
#include <alproxies/alrobotmodelproxy.h>
#include <alproxies/alaudiodeviceproxy.h>
#include <alproxies/alledsproxy.h>
#include <alproxies/alwavingdetectionproxy.h>
#include <alproxies/alautomaticvolumeproxy.h>
#include <alproxies/alsegmentation3dproxy.h>
#include <alproxies/alengagementzonesproxy.h>
#include <alproxies/alsystemproxy.h>
#include <alproxies/alcloseobjectdetectionproxy.h>
#include <alproxies/altouchproxy.h>
#include <alproxies/alfindpersonheadproxy.h>
#include <alproxies/aldarknessdetectionproxy.h>
#include <alproxies/alvideorecorderproxy.h>
#include <alproxies/alfacedetectionproxy.h>
#include <alproxies/alsonarproxy.h>
#include <alproxies/almotionrecorderproxy.h>
#include <alproxies/albatteryproxy.h>
#include <alproxies/alsoundlocalizationproxy.h>
#include <alproxies/alpeopleperceptionproxy.h>
#include <alproxies/allandmarkdetectionproxy.h>
#include <alproxies/alvisualcompassproxy.h>
#include <alproxies/alpreferencemanagerproxy.h>
#include <alproxies/allocalizationproxy.h>
#include <alproxies/almotionproxy.h>
#include <alproxies/alaudiosourcelocalizationproxy.h>
#include <alproxies/alworldrepresentationproxy.h>
#include <alproxies/alsounddetectionproxy.h>
#include <alproxies/alstoreproxy.h>
#include <alproxies/albasicawarenessproxy.h>
#include <alproxies/almemoryproxy.h>
#include <alproxies/alinfraredproxy.h>
#include <alproxies/alheadposeanalysisproxy.h>
#include <alproxies/alvideodeviceproxy.h>
#include <alproxies/allauncherproxy.h>
#include <alproxies/alpanoramacompassproxy.h>
#include <alproxies/alframemanagerproxy.h>
#include <alproxies/alexpressivelisteningproxy.h>
#include <alproxies/altexttospeechproxy.h>
#include <alproxies/alnotificationmanagerproxy.h>
#include <alproxies/alvisiontoolboxproxy.h>
#include <alproxies/alautonomouslifeproxy.h>
#include <alproxies/alvisionrecognitionproxy.h>
#include <alproxies/alfsrproxy.h>
#include <alproxies/albarcodereaderproxy.h>
#include <alproxies/almovementdetection3dproxy.h>
#include <alproxies/albodydetection3dproxy.h>
#include <alproxies/albacklightingdetectionproxy.h>
#include <alproxies/alpreferencesproxy.h>
#include <alproxies/altrackerproxy.h>
#include <alproxies/alconnectionmanagerproxy.h>
#include <alproxies/dcmproxy.h>
#include <alproxies/alloggerproxy.h>
#include <alproxies/alautonomousmovesproxy.h>
#include <alproxies/alredballdetectionproxy.h>
#include <alproxies/alnavigationproxy.h>
#include <alproxies/alspeechrecognitionproxy.h>
#include <alproxies/alchoregrapherecorderproxy.h>
#include <alproxies/aldiagnosisproxy.h>
#include <alproxies/alfilemanagerproxy.h>
#include <alproxies/alpwtiupdateproxy.h>
#include <alproxies/alrobotpostureproxy.h>
#include <alproxies/aldialogproxy.h>
#include <alproxies/albehaviormanagerproxy.h>
#include <alproxies/allaserproxy.h>
#include <alproxies/alfacetrackerproxy.h>
#include <alproxies/alvisualspacehistoryproxy.h>
#include <alproxies/alaudiorecorderproxy.h>
#include <alproxies/alobjectdetectionproxy.h>
#include <alproxies/alanimatedspeechproxy.h>
#include <alproxies/alrobotposeproxy.h>
#include <alproxies/api.h>
#include <alproxies/networkinfo.h>
#include <alproxies/notificationinfo.h>
#endif
