# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(BN-IPC_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(BN-IPC_INCLUDE_DIRS)
   

find_library(BN-IPC_DEBUG_LIBRARY bn-ipc_d)
find_library(BN-IPC_LIBRARY       bn-ipc)


if (BN-IPC_DEBUG_LIBRARY)
  set(BN-IPC_LIBRARIES optimized;${BN-IPC_LIBRARY};debug;${BN-IPC_DEBUG_LIBRARY})
else()
  set(BN-IPC_LIBRARIES ${BN-IPC_LIBRARY})
endif()

set(BN-IPC_LIBRARIES ${BN-IPC_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BN-IPC DEFAULT_MSG
  BN-IPC_LIBRARIES
  BN-IPC_INCLUDE_DIRS
)
set(BN-IPC_PACKAGE_FOUND ${BN-IPC_FOUND} CACHE INTERNAL "" FORCE)
 
set(BN-IPC_DEPENDS "BOOST;BOOST_DATE_TIME;BOOST_SYSTEM" CACHE INTERNAL "" FORCE)
 