# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(LIB_CONFIG_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(LIB_CONFIG_INCLUDE_DIRS)
   

find_library(LIB_CONFIG_DEBUG_LIBRARY lib_config_d)
find_library(LIB_CONFIG_LIBRARY       lib_config)


if (LIB_CONFIG_DEBUG_LIBRARY)
  set(LIB_CONFIG_LIBRARIES optimized;${LIB_CONFIG_LIBRARY};debug;${LIB_CONFIG_DEBUG_LIBRARY})
else()
  set(LIB_CONFIG_LIBRARIES ${LIB_CONFIG_LIBRARY})
endif()

set(LIB_CONFIG_LIBRARIES ${LIB_CONFIG_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIB_CONFIG DEFAULT_MSG
  LIB_CONFIG_LIBRARIES
  LIB_CONFIG_INCLUDE_DIRS
)
set(LIB_CONFIG_PACKAGE_FOUND ${LIB_CONFIG_FOUND} CACHE INTERNAL "" FORCE)
 
set(LIB_CONFIG_DEPENDS "" CACHE INTERNAL "" FORCE)
 